### PR TITLE
Fix #51 specify modifiers for Mac

### LINKED ISSUE #51: rspec fails with 2 errors on Mac :)
````
Failures:

  1) Capybara::Cuprite::Driver has ability to send keys sends sequences with modifiers and symbols
     Failure/Error: expect(input.value).to eq("string")
     
       expected: "string"
            got: "trings"
     
       (compared using ==)
     # ./spec/integration/driver_spec.rb:1303:in `block (3 levels) in <module:Cuprite>'
     # ./spec/integration/driver_spec.rb:14:in `block (2 levels) in <module:Cuprite>'

  2) Capybara::Cuprite::Driver has ability to send keys sends sequences with multiple modifiers and symbols
     Failure/Error: expect(input.value).to eq("s")
     
       expected: "s"
            got: "trings"
     
       (compared using ==)
     # ./spec/integration/driver_spec.rb:1311:in `block (3 levels) in <module:Cuprite>'
     # ./spec/integration/driver_spec.rb:14:in `block (2 levels) in <module:Cuprite>'

Finished in 8 minutes 28 seconds (files took 1.14 seconds to load)
1555 examples, 2 failures, 26 pending

Failed examples:

rspec ./spec/integration/driver_spec.rb:1298 # Capybara::Cuprite::Driver has ability to send keys sends sequences with modifiers and symbols
rspec ./spec/integration/driver_spec.rb:1306 # Capybara::Cuprite::Driver has ability to send keys sends sequences with multiple modifiers and symbols
````

### PR DESCRIPTION
**Pull request by lacostej**

### CODE REVIEW

File: spec/integration/driver_spec.rb [hunk 1]
```diff
@@ -1298,15 +1298,19 @@ def create_screenshot(file, *args)
       it "sends sequences with modifiers and symbols" do
         input = @session.find(:css, "#empty_input")
 
-        input.native.send_keys("t", "r", "i", "n", "g", %i[Ctrl Left], "s")
+        keys = Capybara::Cuprite.mac? ? %i[Alt Left] : %i[Ctrl Left]
```
Comment (route) [inline spec/integration/driver_spec.rb]: Hmm that's weird, phantomjs and poltergeist tests worked everywhere on all platforms. I wonder if it's Chrome issue or feature :)

**Comment by route** [comment]
@lacostej double checked code, looks like everything is correct so I assume it's macos behaviour. Thank you!
